- platform: mjpeg
  mjpeg_url: http://192.168.1.20/axis-cgi/mjpg/video.cgi?resolution=800x600
  username: !secret axis_username
  password: !secret axis_password
  name: Parkering
#- platform: mjpeg
#  mjpeg_url: http://192.168.1.21/axis-cgi/mjpg/video.cgi?resolution=640x480
#  username: !secret axis_username
#  password: !secret axis_password
#  name: TEST
