homeassistant:
  name: Hjemme
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 168
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

zone: !include zones.yaml

zwave:
  usb_path: /dev/ttyACM0

#mqtt: !include services/mqtt.yaml
homekit: !include services/homekit.yaml
netatmo: !include services/netatmo.yaml
tts: !include services/tts.yaml
nest: !include services/nest.yaml
tibber: !include services/tibber.yaml

#INCLUDES
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
climate: !include climate.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
scene: !include scenes.yaml
remote: !include remotes.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
device_tracker: !include device_trackers.yaml
#input_select: !include input_select.yaml
#script: !include scripts.yaml
#notify: !include notify.yaml
#media_player: !include media_players.yaml
#camera: !include cameras.yaml

#Enables
sun:
logbook:
recorder:
#  purge_interval: 1
#  purge_keep_days: 3
history:
conversation:
updater:
frontend:
discovery:
config:
ios:
hassio:
map:
influxdb:
panel_iframe: !include panel_iframe.yaml
